export const books = [
  
  {
    id: 1000,
    titre: 'The Prince Kindle Edition',
    auteur: 'The Prince Kindle Edition',
    category: 'science',
    published_date: '10/5/1998',
    description: 'Uneasy lies the head that wears the crown. The Prince by Machiavelli is echoes that same sentiment in a very elaborate and well-defined manner with all the dos and don ts for the people who hold the power to rule the kingdom. Some have argued that at certain places the book hits hard with satire and talks about how not to rule the state but stating the stark opposite. A great compilation of ideas and thoughts, human nature and ethics that have been discussed in great detail to an extent that concepts have been brainstormed upon so well that one find it easy to conclude.',
    reviews: 2005,
    stars: '3,5 ⭐',
    nbre_page: 20,
    prix: 0.49,
    imageUrl:
      'https://m.media-amazon.com/images/I/41uJ8y-qPLS.jpg',
  },
  {
    id: 1,
    titre: 'math',
    auteur: 'colby convigton',
    category: 'science',
    published_date: '10/5/1998',
    description: 'yes science',
    reviews: 1997,
    stars: '3,5 ⭐',
    nbre_page: 20,
    // prix: '5 $',
    prix: 7.9,
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51n382CyioL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg',
  },
  {
    id: 2,
    titre: 'Poor economics',
    auteur: 'kumaru usman',
    description: 'The winners of the Nobel Prize in Economics upend the most common assumptions about how economics works in this gripping and disruptive portrait of how poor people actually live. Why do the poor borrow to save? Why do they miss out on free life-saving immunizations, but pay for unnecessary drugs? In Poor Economics, Abhijit V. Banerjee and Esther Duflo, two award-winning MIT professors, answer these questions based on years of field research from around the world. Called "marvelous, rewarding" by the Wall Street Journal, the book offers a radical rethinking of the economics of poverty and an intimate view of life on 99 cents a day. Poor Economics shows that creating a world without poverty begins with understanding the daily decisions facing the poor.',
    prix: 500,
    reviews: 8228,
    stars: '⭐⭐⭐⭐',
    category: 'science',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41hV+q2UlkL._SY344_BO1,204,203,200_.jpg',
    published_date: '10/11/2005',
    nbre_page: 50,
  },
  {
    id: 3,
    titre: 'Pure Physique',
    auteur: 'Michael Lipowski',
    description: '',
    prix: 300,
    reviews: 8228,
    stars: '⭐⭐⭐⭐',
    category: 'sport',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41UCrRU88SL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
    published_date: '10/11/2008',
    nbre_page: 20,
  },
  {
    id: 4,
    titre: 'Predictably Irrational',
    auteur: 'Dr. dan ariely',
    description: '',
    prix: 400,
    reviews: 8228,
    stars: '⭐⭐',
    category: 'economics',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/516XdxUXpNL._SX326_BO1,204,203,200_.jpg',
    published_date: '10/11/1997',
    nbre_page: 50,
  },
  {
    id: 5,
    titre: 'The Storyteller: Tales of Life and Music',
    auteur: 'Drave Grohl',
    description: '',    
    prix: 26.94,
    reviews: 8228,
    stars: '4,5 ⭐',
    category: 'Audio Book',
    imageUrl: 'https://m.media-amazon.com/images/I/51PsdEs6H9S.jpg',
    published_date: '10/11/2020',
    nbre_page: 50,
  },
  {
    id: 6,
    titre: 'Geopolitics of blood',
    auteur: 'Safi Said',
    description: '',
    prix: 20,
    reviews: 8228,
    stars: '⭐⭐⭐⭐⭐',
    category: 'politics',
    imageUrl: 'https://m.media-amazon.com/images/I/41Y9jM-Le2L.jpg',
    published_date: '10/11/2020',
    nbre_page: 50,
  },
  {
    id: 7,
    titre: 'The judge s List: A Novel',
    auteur: 'elon musk',
    description: '',
    prix: 30.94,
    reviews: 8228,
    stars: '⭐⭐⭐',
    category: 'Biography',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/71N7vj5cSkL._AC_UL210_SR195,210_.jpg',
    published_date: '10/9/2021',
    nbre_page: 50,
  },
  {
    id: 8,
    titre: 'Ace the Data Science Interview',
    auteur: 'Drave Grohl',
    description: '',
    prix: 30.94, 
    reviews: 8228,
    stars: '⭐⭐⭐⭐⭐',
    category: 'Science',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41A3imtffCL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
    published_date: '10/12/2019',
    nbre_page: 25,
  },
  {
    id: 9,
    titre: 'Deep Learning',
    auteur: 'Drave Grohl',
    description: '',
    prix: 30.94,
    reviews: 4802,
    stars: '4,5 🌟',
    category: 'Science',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/61qbj4KwauL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg',
    published_date: '10/12/2019',
    nbre_page: 47,
  },
  {
    id: 10,
    titre: 'The Complete book of angular 6',
    auteur: 'Nathan Murray',
    description: '',
    prix: 59.5,
    reviews: 4802,
    stars: '🌟🌟🌟',
    category: 'Software framework',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/5189dK2traL._SX384_BO1,204,203,200_.jpg',
    published_date: '09/11/2020',
    nbre_page: 50,
  },
  {
    id: 11,
    titre: 'React.js Book: Learning React JavaScript Library From Scratch',
    auteur: 'Greg Sidelnikov',
    description: '',
    prix: 69.5,
    reviews: 4802,
    stars: '4,5 ⭐',
    category: 'Software framework',
    imageUrl: 'https://m.media-amazon.com/images/I/51BXdIhEe1L._SX260_.jpg',
    published_date: '09/11/2020',
    nbre_page: 60,
  },
  {
    id: 12,
    titre: 'Node Cookbook',
    auteur: 'Bethany Griggs',
    description: '',
    prix: 15.24,
    reviews: 4802,
    stars: '⭐⭐⭐⭐',
    category: 'Software framework',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51tPFqRdrjL._SY445_SX342_QL70_FMwebp_.jpg',
    published_date: '09/11/2021',
    nbre_page: 40,
  },
];
